### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by Terenor** [tr4wzified/KnowYourEnemyPatcher#20] opened 2021-08-01 09:01 UTC
Hi there,

i get an error message and can't figure out what it means. Probably a user error, because it worked in the past. Would appreciate your help.

System.ArgumentException: An item with the same key has already been added. Key: 0F2595:Skyrim.esm
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Noggog.Cache`2.Add(TObject item) in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Containers\Cache.cs:line 103
   at KnowYourEnemyMutagen.Program.RunPatch(IPatcherState`2 state) in C:\Users\fredd\AppData\Local\Temp\Synthesis\l3g1w2iq.tys\Git\nkpls1kc.kxw\Runner\KnowYourEnemyMutagen\Program.cs:line 149
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 88
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, ModKey exportKey) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 448
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 397
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 372
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel)
   at Synthesis.Bethesda.Execution.Runner.Run[TKey](String workingDirectory, ModPath outputPath, String dataFolder, IEnumerable`1 loadOrder, GameRelease release, IEnumerable`1 patchers, IRunReporter`1 reporter, CancellationToken cancellation, ModPath sourcePath, PersistenceMode persistenceMode, String persistencePath)

**Comment by tr4wzified** [comment] 2021-09-06 10:30
Does this still happen? Make sure you don't have Synthesis.esp active while regenerating it.

**Comment by Glanzer-modder** [comment] 2021-09-07 23:05
I got the exact same error after running KnowYourEnemyPatcher for the first time (after switching from the zedit patcher). Other Synthesis patches work fine. The Synthesis.esp was removed before patching. Will go back to zedit for now. Glad to do anything on my side to help debug.

**Comment by tr4wzified** [comment] 2021-09-08 13:50
Can you guys try again now, with the latest version of the patcher? It should auto-update in Synthesis - if it still refuses, please post the full Synthesis log file so I can have another look.

**Comment by Glanzer-modder** [comment] 2021-09-08 14:57
Same error unfortunately. Output is in the link below (>11k lines, too big for pastebin). Let me know if you need anything else!

https://drive.google.com/file/d/1m116iYDh43svAhZrNZuhM3_s4FtTMw2Z/view?usp=sharing

**Comment by Terenor** [comment] 2021-09-08 18:23
Sorry, forgot to mention. I reinstalled synthesis and all patchers and it worked.

**Comment by Glanzer-modder** [comment] 2021-09-08 19:34
I created a new MO2 profile with nothing enabled in it except the 5 vanilla ESMs and the Know Your Enemy Plugin. Then I ran just the KnowYourEnemy Synthesis patcher and it ran without errors. So there is some incompatibility in my mix of mods that's causing the errors. Looks like the ball is in my court. It will take some time to narrow down the cause because I have over 700 mods. If you have any suggestions that could help narrow down the search I'd appreciate it. First thing I'm going to do is to make sure that one offending record isn't accidentally duplicated somewhere.

**Comment by Glanzer-modder** [comment] 2021-09-08 20:43
Ok, it didn't take long to figure out what the problem was. LOL What's causing the problem is if another patcher has already patched a record, the KnowYourEnemyPatcher finds that and considers it to already be patched. This means that KnowYourEnemyPatcher will always run successfully if it's first in the Synthesis patcher list.

In my case, the Engarde patcher patches record 000F2595 first and places that in the "done" queue somewhere in Synthesis. Then when the KnowYourEnemyPatcher comes along and grabs that record from Skyrim.esm, it already finds it in the "done" queue and that causes the error. If I move the KnowYourEnemyPatcher ABOVE the Engarde patcher in the patcher list in Synthesis so that it runs first, then no error occurs and all the patchers complete without errors.

This makes me think that the KnowYourEnemyPatcher isn't including the "done" queue when it searches for winning override records. It should look there first and patch the record there if it finds it. That's just a guess.

If you want to duplicate this, it's easy to do, just download the Engarde plugin, put it in your load order, then install the Engarde Synthesis patch from github and move it to the top of the patcher list above KnowYourEnemyPatcher (by dragging/dropping), then run Synthesis.

**Comment by theSkyseS** [comment] 2021-09-24 07:58
This one is should be fixed with 7b6d4fb

**Comment by tr4wzified** [comment] 2021-09-24 20:31
Yup. Forgot to close it

**Closed as completed by tr4wzified** 2021-09-24 20:31 UTC
